from __future__ import annotations

import json
from pathlib import Path

from .base import ClientAdapter


class ClaudeAdapter(ClientAdapter):
    client_id = "claude"

    def expected_files(self, root: Path) -> list[Path]:
        return [root / "CLAUDE.md", root / ".mcp.json"]

    def read_configured_endpoint(self, root: Path) -> str | None:
        mcp = root / ".mcp.json"
        if not mcp.exists():
            return None
        data = json.loads(mcp.read_text(encoding="utf-8"))
        server = data.get("mcpServers", {}).get("ctx-engine", {})
        endpoint = server.get("url")
        return str(endpoint) if endpoint else None

    def write_files(self, root: Path, endpoint: str) -> list[Path]:
        claude = root / "CLAUDE.md"
        mcp = root / ".mcp.json"
        claude.write_text(
            f"""# CLAUDE.md - generated by ctx-engine

Source of truth: `.ctx-engine/rules.yaml`

Use ctx-engine as the single project context gateway.

MCP endpoint:

```text
{endpoint}
```

Do not connect separate docs, memory, code graph, shell, or write-tool MCP servers directly unless the user explicitly approves.

Use ctx-engine capsules before significant edits, debugging, migrations, or repo analysis.

Private code and private docs stay local. Context7 is public documentation only.
""",
            encoding="utf-8",
        )
        mcp.write_text(
            json.dumps(
                {
                    "mcpServers": {
                        "ctx-engine": {
                            "type": "http",
                            "url": endpoint,
                        }
                    }
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return [claude, mcp]
