from __future__ import annotations

import tomllib
from pathlib import Path

from .base import ClientAdapter


class CodexAdapter(ClientAdapter):
    client_id = "codex"

    def expected_files(self, root: Path) -> list[Path]:
        return [root / "AGENTS.md", root / ".codex" / "config.toml"]

    def read_configured_endpoint(self, root: Path) -> str | None:
        config = root / ".codex" / "config.toml"
        if not config.exists():
            return None
        data = tomllib.loads(config.read_text(encoding="utf-8"))
        server = data.get("mcp_servers", {}).get("ctx_engine", {})
        endpoint = server.get("url")
        return str(endpoint) if endpoint else None

    def write_files(self, root: Path, endpoint: str) -> list[Path]:
        agents = root / "AGENTS.md"
        codex_dir = root / ".codex"
        codex_dir.mkdir(parents=True, exist_ok=True)
        config = codex_dir / "config.toml"
        agents.write_text(
            f"""# AGENTS.md - generated by ctx-engine

Source of truth: `.ctx-engine/rules.yaml`

Use ctx-engine as the single project MCP context gateway before non-trivial code work.

MCP endpoint:

```text
{endpoint}
```

Do not connect Codex directly to separate docs, memory, code graph, shell, or write-tool MCP servers unless the user explicitly approves.

Privacy:

- Private source code and private docs stay local.
- Context7 is public documentation only.
- Secrets and ignored files must not appear in capsules, cache, or ledger.

Validation notes should include files changed, suggested tests, risks, and commands run.
""",
            encoding="utf-8",
        )
        config.write_text(
            f"""# generated by ctx-engine from .ctx-engine/rules.yaml
project_doc_fallback_filenames = ["AGENTS.md", "CLAUDE.md", "GEMINI.md"]
project_doc_max_bytes = 65536

[mcp_servers.ctx_engine]
url = "{endpoint}"
startup_timeout_sec = 20
tool_timeout_sec = 60
enabled = true
enabled_tools = [
  "workspace_register",
  "workspace_list",
  "index_repository",
  "search_symbols",
  "get_file_skeleton",
  "get_symbol_context",
  "get_symbol_references",
  "get_change_impact",
  "get_blast_radius",
  "get_context_capsule",
  "resolve_docs_context",
  "write_session_memory",
  "read_session_memory",
  "get_action_ledger",
  "get_doctor_status"
]
""",
            encoding="utf-8",
        )
        return [agents, config]
