from __future__ import annotations

import json
from pathlib import Path

from .base import ClientAdapter


class GeminiAdapter(ClientAdapter):
    client_id = "gemini"

    def expected_files(self, root: Path) -> list[Path]:
        return [root / "GEMINI.md", root / ".gemini" / "settings.json"]

    def read_configured_endpoint(self, root: Path) -> str | None:
        settings = root / ".gemini" / "settings.json"
        if not settings.exists():
            return None
        data = json.loads(settings.read_text(encoding="utf-8"))
        server = data.get("mcpServers", {}).get("ctx-engine", {})
        endpoint = server.get("httpUrl")
        return str(endpoint) if endpoint else None

    def write_files(self, root: Path, endpoint: str) -> list[Path]:
        gemini_doc = root / "GEMINI.md"
        gemini_dir = root / ".gemini"
        gemini_dir.mkdir(parents=True, exist_ok=True)
        settings = gemini_dir / "settings.json"
        gemini_doc.write_text(
            f"""# GEMINI.md - generated by ctx-engine

Source of truth: `.ctx-engine/rules.yaml`

Use ctx-engine as the project context gateway.

MCP endpoint:

```text
{endpoint}
```

Recommended mode for sensitive repositories:

```text
ctx serve --mode offline
```

Use sandboxing where available. Do not send private source code, private docs, secrets, or full prompts to external providers.
""",
            encoding="utf-8",
        )
        settings.write_text(
            json.dumps(
                {
                    "mcp": {"allowed": ["ctx-engine"]},
                    "mcpServers": {
                        "ctx-engine": {
                            "httpUrl": endpoint,
                            "timeout": 30000,
                            "trust": False,
                        }
                    },
                },
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return [gemini_doc, settings]
