from __future__ import annotations

import json

from ctx_engine.client_adapters import ClaudeAdapter, CodexAdapter, GeminiAdapter, GenericAdapter


def test_client_adapters_generate_files(tmp_path):
    CodexAdapter().install(tmp_path)
    ClaudeAdapter().install(tmp_path)
    GeminiAdapter().install(tmp_path)
    assert (tmp_path / "AGENTS.md").exists()
    assert (tmp_path / ".codex" / "config.toml").exists()
    assert (tmp_path / "CLAUDE.md").exists()
    assert (tmp_path / ".mcp.json").exists()
    assert (tmp_path / "GEMINI.md").exists()
    assert (tmp_path / ".gemini" / "settings.json").exists()
    assert "generated by ctx-engine" in (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "ctx hooks plan codex" in (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
    assert "ctx hooks plan claude" in (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert "ctx hooks plan gemini" in (tmp_path / "GEMINI.md").read_text(encoding="utf-8")
    gemini_settings = json.loads((tmp_path / ".gemini" / "settings.json").read_text(encoding="utf-8"))
    assert gemini_settings["mcpServers"]["ctx-engine"]["httpUrl"] == "http://127.0.0.1:7331/mcp"


def test_client_adapter_status_reports_missing_and_installed(tmp_path):
    codex = CodexAdapter()
    missing = codex.status(tmp_path)
    assert missing["installed"] is False
    assert "AGENTS.md" in missing["missing_files"]

    codex.install(tmp_path)
    installed = codex.status(tmp_path)
    assert installed["installed"] is True
    assert installed["configured_endpoint"] == "http://127.0.0.1:7331/mcp"
    assert installed["endpoint_matches_rules"] is True

    GenericAdapter().install(tmp_path)
    assert GenericAdapter().status(tmp_path)["installed"] is True
