from __future__ import annotations

import os
import re
from pathlib import Path

from . import __version__

DEFAULT_ENDPOINT = "http://127.0.0.1:7331/mcp"
DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 7331
SUPPORTED_MODES = {"safe", "dev", "offline", "audit"}

IGNORED_PATHS = [
    ".git/**",
    "node_modules/**",
    "dist/**",
    "build/**",
    ".venv/**",
    "venv/**",
    "__pycache__/**",
    ".env",
    ".env.*",
    "*.pem",
    "*.key",
    "*.p12",
    "*.sqlite",
    "*.db",
    "*.dump",
]


def package_root() -> Path:
    return Path(__file__).resolve().parent


def project_root() -> Path:
    return package_root().parent


def data_dir() -> Path:
    value = os.environ.get("CTX_ENGINE_DATA_DIR")
    if value:
        return Path(value).expanduser()
    if Path("/data").exists() and os.environ.get("CTX_ENGINE_IN_DOCKER") == "1":
        return Path("/data")
    return Path.home() / ".ctx-engine"


def db_path() -> Path:
    value = os.environ.get("CTX_ENGINE_DB")
    return Path(value).expanduser() if value else data_dir() / "ctx-engine.sqlite"


def current_mode(default: str = "safe") -> str:
    mode = os.environ.get("CTX_ENGINE_MODE", default).lower()
    return mode if mode in SUPPORTED_MODES else default


def config_dir(workspace: Path) -> Path:
    return workspace / ".ctx-engine"


def rules_path(workspace: Path) -> Path:
    return config_dir(workspace) / "rules.yaml"


def config_path(workspace: Path) -> Path:
    return config_dir(workspace) / "config.yaml"


def default_config_text(workspace: Path) -> str:
    root = str(workspace.resolve())
    ignored = "\n".join(f"    - {item!r}" for item in IGNORED_PATHS)
    return f"""# generated by ctx-engine {__version__}
workspace:
  name: default
  root: {root!r}
  read_only: true

server:
  host: {DEFAULT_HOST}
  port: {DEFAULT_PORT}
  transport: http
  default_mode: safe

providers:
  code_graph:
    enabled: true
    languages: [python, javascript, typescript]
  build_test:
    enabled: true
  local_docs:
    enabled: true
  context7:
    enabled: true
    public_docs_only: true
    send_private_code: false
  memory:
    enabled: true
    backend: sqlite
  cache:
    exact_cache: true
    docs_cache: true
    capsule_cache: true

safety:
  read_only: true
  no_shell_tools: true
  no_write_tools: true
  external_provider_privacy_guard: true
  secret_redaction: true
  ignored_paths:
{ignored}

ledger:
  enabled: true
  include_client_id: true
"""


def default_rules_text(endpoint: str = DEFAULT_ENDPOINT) -> str:
    return f"""# generated by ctx-engine {__version__}
source_of_truth: .ctx-engine/rules.yaml
endpoint: {endpoint}
gateway:
  single_mcp_endpoint: true
  no_downstream_mcp_exposure: true
  no_shell_tools: true
  no_write_tools: true
privacy:
  private_code_stays_local: true
  private_docs_stay_local: true
  context7_public_docs_only: true
  redact_secrets: true
clients:
  codex: true
  claude: true
  gemini: true
priority:
  - current user instruction
  - .ctx-engine/rules.yaml
  - current code and tests
  - local docs and ADRs
  - Context7 public docs
  - verified memory
  - unverified memory
"""


def ensure_project_config(workspace: Path, endpoint: str = DEFAULT_ENDPOINT) -> list[Path]:
    workspace = workspace.resolve()
    cfg_dir = config_dir(workspace)
    cfg_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    cfg = config_path(workspace)
    if not cfg.exists():
        cfg.write_text(default_config_text(workspace), encoding="utf-8")
        written.append(cfg)
    rules = rules_path(workspace)
    if not rules.exists():
        rules.write_text(default_rules_text(endpoint), encoding="utf-8")
        written.append(rules)
    return written


def load_endpoint_from_rules(workspace: Path) -> str:
    path = rules_path(workspace)
    if not path.exists():
        return DEFAULT_ENDPOINT
    text = path.read_text(encoding="utf-8", errors="replace")
    match = re.search(r"(?m)^\s*endpoint\s*:\s*(.+?)\s*$", text)
    if not match:
        return DEFAULT_ENDPOINT
    return match.group(1).strip().strip("'\"")
