from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any

from .db import stable_json
from .workflow import RECIPES, show_workflow, suggest_workflow


def list_skill_packs() -> dict[str, Any]:
    packs = []
    for name in sorted(RECIPES):
        recipe = RECIPES[name]
        packs.append(
            {
                "name": f"ctx-{name}",
                "source_recipe": name,
                "intent": recipe["intent"],
                "install_mode": "manual",
                "auto_install": False,
            }
        )
    return {"status": "ok", "count": len(packs), "skill_packs": packs}


def build_skill_pack(name_or_query: str) -> dict[str, Any]:
    recipe_result = show_workflow(name_or_query)
    selected_by = "name"
    if recipe_result["status"] != "ok":
        suggestion = suggest_workflow(name_or_query)
        recipe_result = suggestion["recipe"]
        selected_by = "query"

    recipe = {key: value for key, value in recipe_result.items() if key != "status"}
    source_recipe = str(recipe["name"])
    skill_name = f"ctx-{source_recipe}"
    markdown = _skill_markdown(skill_name, recipe)
    manifest = {
        "name": skill_name,
        "version": "0.1.0",
        "generated_by": "ctx-engine",
        "source_recipe": source_recipe,
        "selected_by": selected_by,
        "install_mode": "manual",
        "auto_install": False,
        "files": ["SKILL.md"],
        "safety": {
            "executable": False,
            "mcp_surface_changed": False,
            "private_data_egress": False,
        },
    }
    return {
        "status": "ok",
        "name": skill_name,
        "source_recipe": source_recipe,
        "selected_by": selected_by,
        "manifest": manifest,
        "files": [
            {
                "path": "SKILL.md",
                "sha256": hashlib.sha256(markdown.encode("utf-8")).hexdigest(),
                "content": markdown,
            }
        ],
        "warnings": [
            "Skill pack generation is advisory and does not install executable skills or change MCP tools."
        ],
    }


def render_skill_pack(pack: dict[str, Any], output_format: str = "json") -> str:
    if output_format == "markdown":
        return str(pack["files"][0]["content"])
    if output_format == "json":
        return json.dumps(pack, ensure_ascii=False, indent=2, sort_keys=True, default=str)
    raise ValueError("format must be json or markdown")


def write_skill_pack(pack: dict[str, Any], output: str | Path) -> dict[str, Any]:
    target = Path(output).resolve()
    target.mkdir(parents=True, exist_ok=True)
    skill_path = target / "SKILL.md"
    manifest_path = target / "skill-pack.json"
    skill_path.write_text(str(pack["files"][0]["content"]), encoding="utf-8")
    manifest_path.write_text(stable_json(pack["manifest"]) + "\n", encoding="utf-8")
    return {
        "status": "ok",
        "output_path": str(target),
        "written": [str(skill_path), str(manifest_path)],
        "skill_pack": {
            "name": pack["name"],
            "source_recipe": pack["source_recipe"],
            "install_mode": pack["manifest"]["install_mode"],
            "auto_install": pack["manifest"]["auto_install"],
        },
    }


def _skill_markdown(skill_name: str, recipe: dict[str, Any]) -> str:
    steps = "\n".join(f"{index}. {step}" for index, step in enumerate(recipe["steps"], start=1))
    commands = "\n".join(f"- `{command}`" for command in recipe["recommended_commands"])
    context = "\n".join(f"- `{item}`" for item in recipe["required_context"])
    safety = "\n".join(f"- {item}" for item in recipe["safety_notes"])
    return f"""# {skill_name}

Generated by ctx-engine from workflow recipe `{recipe["name"]}`.

## Intent

{recipe["intent"]}

## Workflow

{steps}

## Recommended Commands

{commands}

## Required Context

{context}

## Safety Notes

{safety}
- This generated skill pack is advisory only.
- Do not install or execute generated skill content without explicit user approval.
- Do not add shell/write MCP tools or downstream MCP servers through this skill pack.
"""
